### ISSUE TITLE
XML not being read in from custom model

### ISSUE THREAD

**Issue by opoudjis** [lutaml/lutaml-model#117]
Another blocker.

Consider the following code, which uses an externally defined class for content:

````
require "lutaml/model"
require "lutaml/model/xml_adapter/nokogiri_adapter"
require "relaton"
require "relaton/cli"

Lutaml::Model::Config.configure do |config|
  config.xml_adapter = Lutaml::Model::XmlAdapter::NokogiriAdapter
  config.yaml_adapter = Lutaml::Model::YamlAdapter::StandardYamlAdapter
  config.json_adapter = Lutaml::Model::JsonAdapter::StandardJsonAdapter
end

module SimpleModel
  class Bibdata < Lutaml::Model::Serializable
    # attribute :code, :string
    model ::RelatonBib::BibliographicItem
  end

  class Address < Lutaml::Model::Serializable
    attribute :street, :string, raw: true
    attribute :city, :string, raw: true
    attribute :bibdata, Bibdata

    yaml do
      map "street", to: :street
      map "city", to: :city
      map "bibdata", to: :bibdata, with: { from: :bibdata_from_yaml,
                                           to: :bibdata_to_yaml }
    end

    xml do
      root "address"
      map_element "street", to: :street # ,  with: { from: :street_from_xml, to: :street_to_xml }
      map_element "city", to: :city # , with: { from: :city_from_xml, to: :city_to_xml }
      map_element "bibdata", to: :bibdata, with: { from: :bibdata_from_xml,
                                                   to: :bibdata_to_xml }
    end

    def bibdata_from_yaml(model, value)
      value and !value.empty? or return
      model.bibdata = ::Relaton::Cli::YAMLConvertor.convert_single_file(value)
    end 

    def bibdata_to_yaml(model, doc)
      doc["bibdata"] = model.bibdata&.to_hash
    end 

    def bibdata_from_xml(model, node)
      model.bibdata = node # Relaton::Cli.parse_xml(node.content)
    end 

    def bibdata_to_xml(model, parent, doc)
      b = model.bibdata or return
      elem = b.to_xml(bibdata: true, date_format: :full)
      doc.add_element(parent, elem)
    end 

    def city_from_xml(model, node)
      model.city = node
    end

    def city_to_xml(model, parent, doc)
      doc.add_element(parent, "<city>#{model.city}</city>")
    end

    def street_from_xml(model, node)
      model.street = node
    end

    def street_to_xml(model, parent, doc)
      doc.add_element(parent, "<street>#{model.street}</street>")
    end
  end


  xml = <<~XML
      <address>
      <street>
          A <p>b</p> B <p>c</p> C
      </street>
      <bibdata type="collection" schema-version="v1.2.8">  <title type="title-main" format="text/plain" language="en">JCGM Collection 1</title>
      <docidentifier type="iso">JCGM 12345</docidentifier>
      <date type="created">
        <on>2020-01-01</on>
      </date>
      <date type="issued">
        <on>2020-01-01</on>
      </date>
      <edition>1</edition>
      <copyright>
        <from>2020</from>
        <owner>
          <organization>
            <name>International Organization for Standardization</name>
            <abbreviation>JCMG</abbreviation>
          </organization>
        </owner>
      </copyright>
    </bibdata>
      </address>
  XML

  yaml = <<~YAML
    street: A <a>N</a> B
    city: B <a>N</a> B
    bibdata:
      title:
        type: title-main
        language: en
        content: JCGM Collection 1
      type: collection
      docid:
        type: iso
        id: JCGM 12345
      edition: 1
      date:
        - type: created
          value: "2020"
        - type: issued
          value: "2020"
      copyright:
        owner:
          name: International Organization for Standardization
          abbreviation: JCMG
        from: "2020"
  YAML

  puts "YAML > YAML"
  sample = SimpleModel::Address.from_yaml(yaml).to_yaml
  puts sample
  puts "XML > YAML"
  sample = SimpleModel::Address.from_xml(xml).to_yaml
  puts sample
  puts "YAML > XML"
  sample = SimpleModel::Address.from_yaml(yaml).to_xml
  puts sample
  puts "XML > XML"
  sample = SimpleModel::Address.from_xml(xml).to_xml
  puts sample
````

And I am not going to come up with a simple test class instead of ::RelatonBib::BibliographicItem, because after three months of this, I'm not going to spend an extra couple of hours doing mockups.

The custom model is working fine for reading YAML, via ::Relaton::Cli::YAMLConvertor.convert_single_file(value). Both the YAML and the XML outputs work.

The custom model fails to read the XML, other than the schema-version attribute: all it outputs is:

````
<bibdata schema-version="v1.2.9"/>
````

````
bibdata:
  schema-version: v1.2.9
````

And from debugging, this issue appears to be happening right in mapping_hash: in Lutaml::Model::Serialize::ClassMethods#apply_mappings, doc.to_xml has bibdata in it intact:

````
"<metanorma-collection>\n  <bibdata type=\"collection\">\n    <title type=\"title-main\" format=\"text/plain\" language=\"en\">ISO Collection 1</title>\n    <docidentifier type=\"iso\">ISO 12345</docidentifier>\n    <date type=\"created\">\n      <on>2020-01-01</on>\n    </date>\n    <date type=\"issued\">\n      <on>2020-01-01</on>\n    </date>\n    <edition>1</edition>\n    <copyright>\n      <from>2020</from>\n      <owner>\n        <organization>\n          <name>International Organization for Standardization</name>\n          <abbreviation>ISO</abbreviation>\n        </organization>\n      </owner>\n    </copyright>\n  </bibdata>\n  <directive>\n    <key>documents-external</key>\n....
````

But the conversion to mapping_hash in 

````
doc_hash = doc.parse_element(doc.root, self, :xml)
````

ignores all the content but the schema-version attribute:

````
=> {"text"=>["\n  ", "\n  ", "\n  ", "\n  ", "\n  ", "\n  ", "\n  ", "\n  ", "\n"], "bibdata"=>{"text"=>["\n    ", "\n    ", "\n    ", "\n    ", "\n    ", "\n    ", "\n  "], "title"=>{"text"=>"ISO Collection 1", "type"=>"title-main", "format"=>"text/plain", "language"=>"en"}, "docidentifier"=>{"text"=>"ISO 12345", "type"=>"iso"}, "date"=>[{"text"=>["\n      ", "\n    "], "on"=>{"text"=>"2020-01-01"}, "type"=>"created"}, {"text"=>["\n      ", "\n    "], "on"=>{"text"=>"2020-01-01"}, "type"=>"issued"}], "edition"=>{"text"=>"1"}, "copyright"=>{"text"=>["\n      ", "\n      ", "\n    "], "from"=>{"text"=>"2020"}, "owner"=>{"text"=>["\n        ", "\n      "], "organization"=>{"text"=>["\n          ", "\n          ", "\n        "], "name"=>{"text"=>"International Organization for Standardization"}, "abbreviation"=>{"text"=>"ISO"}}}}, "type"=>"collection"}, "directive"=>[{"text"=>["\n    ", "\n  "], "key"=>{"text"=>"documents-external"}}, {"text"=>["\n    ", "\n    ", "\n  "], "key"=>{"text"=>"coverpage"}, "value"=>{"text"=>"spec/fixtures/collection/collection_cover.html"}}], "entry"=>{"text"=>["\n    ", "\n    ", "\n    ", "\n    ", "\n    ", "\n    ", "\n  "], "identifier"=>{"text"=>"_"}, "type"=>{"text"=>"collection"}, "title"=>{"text"=>"ISO Collection"}, "entry"=>[{"text"=>["\n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "], "identifier"=>{"text"=>"_"}, "type"=>{"text"=>"subcollection"}, "title"=>{"text"=>"Standards"}, "entry"=>[{"text"=>["\n        ", "\n        ", "\n      "], "identifier"=>{"text"=>"ISO 17301-1:2016"}, "bibdata"=>{"text"=>["\n          ", "\n          ", "\n          ", "\n          ", "\n          ", "\n          ", "\n          ", "\n          ", "\n          ", "\n          ", "\n          ", "\n          ", "\n          ", "\n          ", "\n          ", "\n          ", "\n          ", "\n          ", "\n          ", "\n          ", "\n          ", "\n          ", "\n        "], 
````

And I sure it is doing so because of the foundational problem with mapping_hash which I have pointed out, that it does not cope with mixed content, or with leading whitespace.

In fact, when I make 

````
    xml do
      root "address", mixed: true
````

which should be coping with mixed content, not only does XML > YAML fail to output the bibdata, but XML > XML crashes:

````
/Users/nickn/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/lutaml-model-0.3.14/lib/lutaml/model/xml_adapter/xml_document.rb:142:in `add_to_xml': undefined method `new' for nil (NoMethodError)

            options[:mapper_class].new.send(rule.custom_methods[:to], element, xml.parent, xml)
                                  ^^^^
	from /Users/nickn/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/lutaml-model-0.3.14/lib/lutaml/model/xml_adapter/nokogiri_adapter.rb:83:in `block (2 levels) in build_ordered_element'
````

**Comment by ronaldtse** [comment]
@HassanAkbar @suleman-uzair has this PR fixed this issue?

https://github.com/lutaml/lutaml-model/pull/119

**Comment by HassanAkbar** [comment]
@ronaldtse 

> @HassanAkbar @suleman-uzair has this PR fixed this issue?
> 
> #119

#119 will not fix this issue; it was for a separate issue that occurred when using custom models with the `render_default` check.

**Comment by ronaldtse** [comment]
Got it.

**Comment by ronaldtse** [comment]
@HassanAkbar so #126 fixes part of this problem but not fully?

**Comment by HassanAkbar** [comment]
@ronaldtse It fixes the crash and adds an internal representation of the node to the mapping hash. So I think this problem is fully solved by #126.

@opoudjis Is there something else needed for this ticket?

**Comment by ronaldtse** [comment]
The latest gem is released for this.

@opoudjis could you please help try if this works? Thanks.

**Comment by opoudjis** [comment]
> @ronaldtse It fixes the crash and adds an internal representation of the node to the mapping hash. So I think this problem is fully solved by #126.
> 
> @opoudjis Is there something else needed for this ticket?

This continues not to work. The crash has not gone away. And what output it does generate from processing XML is completely unacceptable. The XML > YAML output is nonsensical:

````
bibdata: !ruby/hash-with-ivars:Lutaml::Model::MappingHash
  ivars:
    :@ordered: false
    :@item_order:
    - text
    - title
    - text
    - docidentifier
    - text
    - date
    - text
    - date
    - text
    - edition
    - text
    - copyright
    - text
    :@node: &2 !ruby/object:Lutaml::Model::XmlAdapter::NokogiriElement
      name: bibdata
      namespace_prefix:
      attributes:
        type: !ruby/object:Lutaml::Model::XmlAdapter::XmlAttribute
          name: type
          value: collection
          namespace:
          namespace_prefix:
        schema-version: !ruby/object:Lutaml::Model::XmlAdapter::XmlAttribute
          name: schema-version
          value: v1.2.8
          namespace:
          namespace_prefix:
````

And the XML > XML output crashes with:

````
/Users/nickn/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/lutaml-model-0.3.19/lib/lutaml/model/mapping_hash.rb:39:in `method_missing': undefined method `to_xml' for an instance of Lutaml::Model::MappingHash (NoMethodError)
Did you mean?  to_yaml
	from a2.rb:53:in `bibdata_to_xml'
	from /Users/nickn/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/lutaml-model-0.3.19/lib/lutaml/model/xml_adapter/xml_document.rb:139:in `add_to_xml'
	from /Users/nickn/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/lutaml-model-0.3.19/lib/lutaml/model/xml_adapter/nokogiri_adapter.rb:82:in `block (2 levels) in build_ordered_element'
	from /Users/nickn/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/lutaml-model-0.3.19/lib/lutaml/model/xml_adapter/nokogiri_adapter.rb:61:in `each'
	from /Users/nickn/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/lutaml-model-0.3.19/lib/lutaml/model/xml_adapter/nokogiri_adapter.rb:61:in `block in build_ordered_element'
	from /Users/nickn/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/nokogiri-1.16.7-arm64-darwin/lib/nokogiri/xml/builder.rb:433:in `insert'
	from /Users/nickn/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/nokogiri-1.16.7-arm64-darwin/lib/nokogiri/xml/builder.rb:415:in `method_missing'
	from /Users/nickn/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/lutaml-model-0.3.19/lib/lutaml/model/xml_adapter/builder/nokogiri.rb:68:in `public_send'
	from /Users/nickn/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/lutaml-model-0.3.19/lib/lutaml/model/xml_adapter/builder/nokogiri.rb:68:in `method_missing'
	from /Users/nickn/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/lutaml-model-0.3.19/lib/lutaml/model/xml_adapter/nokogiri_adapter.rb:53:in `public_send'
	from /Users/nickn/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/lutaml-model-0.3.19/lib/lutaml/model/xml_adapter/nokogiri_adapter.rb:53:in `build_ordered_element'
	from /Users/nickn/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/lutaml-model-0.3.19/lib/lutaml/model/xml_adapter/xml_document.rb:120:in `build_element'
	from /Users/nickn/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/lutaml-model-0.3.19/lib/lutaml/model/xml_adapter/nokogiri_adapter.rb:23:in `block in to_xml'
	from /Users/nickn/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/lutaml-model-0.3.19/lib/lutaml/model/xml_adapter/builder/nokogiri.rb:9:in `block in build'
	from /Users/nickn/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/nokogiri-1.16.7-arm64-darwin/lib/nokogiri/xml/builder.rb:331:in `initialize'
	from /Users/nickn/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/lutaml-model-0.3.19/lib/lutaml/model/xml_adapter/builder/nokogiri.rb:8:in `new'
	from /Users/nickn/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/lutaml-model-0.3.19/lib/lutaml/model/xml_adapter/builder/nokogiri.rb:8:in `build'
	from /Users/nickn/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/lutaml-model-0.3.19/lib/lutaml/model/xml_adapter/nokogiri_adapter.rb:16:in `to_xml'
	from /Users/nickn/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/lutaml-model-0.3.19/lib/lutaml/model/serialize.rb:528:in `public_send'
	from /Users/nickn/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/lutaml-model-0.3.19/lib/lutaml/model/serialize.rb:528:in `block (2 levels) in <module:Serialize>'
	from a2.rb:137:in `<module:SimpleModel>'
	from a2.rb:12:in `<main>'
````

This being run with the latest lutaml-model:

````
bundle info lutaml-modelork/ribose/metanorma[fix/lutaml-model] $ bundle exec ruby a2.rb
  * lutaml-model (0.3.19)
	Summary: LutaML creating data models in Ruby
	Homepage: https://github.com/lutaml/lutaml-model
	Path: /Users/nickn/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/lutaml-model-0.3.19
	Reverse Dependencies: 
		loc_mods (0.2.5) depends on lutaml-model (>= 0)
````

I have posted the Ruby script above that I need to work. I have copy pasted it to ensure you were given correct input.

 It does not work. It must work.

**Comment by ronaldtse** [comment]
Instead of going back and forth, @HassanAkbar can you directly debug the branch that @opoudjis is working on? @opoudjis could you please help provide instructions on how to reproduce this issue? Thanks!

**Comment by HassanAkbar** [comment]
> Instead of going back and forth, @HassanAkbar can you directly debug the branch that @opoudjis is working on? @opoudjis could you please help provide instructions on how to reproduce this issue? Thanks!

@ronaldtse / @opoudjis I am looking into it.

**Comment by HassanAkbar** [comment]
@opoudjis The crashes are due to custom methods and how we are setting values inside them, 

- ### For XML > XML

  Currently we are setting `model.bibdata` to the node passed in the `bibdata_from_xml` method which is a mapping hash and then when converting back to XML in `bibdata_to_xml` we are calling `to_xml` method which is not present on the mapping hash resulting in a crash.

  Changing the `bibdata_from_xml` to something like below should work.

  ```ruby
  def bibdata_from_xml(model, node)
    model.bibdata = Relaton::Cli.parse_xml(node.node.adapter_node)
  end
  ```

- ### For XML > YAML

  Similarly here we set the `model.bibdata` to `mapping_hash` in `bibdata_from_xml`, and then that mapping hash is turned into Yaml, so the output we see is yaml representation of the internal structure.

  So changing the above method should fix both of the issues.

Attaching output after changing the above method below. 

- XML > YAML

  ```yaml
  street: "\n      A <p>b</p> B <p>c</p> C\n  "
  bibdata:
    schema-version: v1.2.9
    id: JCGM12345
    title:
    - content: JCGM Collection 1
      language:
      - en
      format: text/plain
      type: title-main
    type: collection
    docid:
    - id: JCGM 12345
      type: iso
    date:
    - type: created
      value: '2020-01-01'
    - type: issued
      value: '2020-01-01'
    edition:
      content: '1'
    copyright:
    - owner:
      - name:
        - content: International Organization for Standardization
        abbreviation:
          content: JCMG
      from: '2020'
    ext:
      schema-version: v1.0.3

  ```

- XML > XML

  ```xml
  <address><street>
        A <p>b</p> B <p>c</p> C
    </street><bibdata type="collection" schema-version="v1.2.9">
    <title type="title-main" format="text/plain" language="en">JCGM Collection 1</title>
    <docidentifier type="iso">JCGM 12345</docidentifier>
    <date type="created">
      <on>2020-01-01</on>
    </date>
    <date type="issued">
      <on>2020-01-01</on>
    </date>
    <edition>1</edition>
    <copyright>
      <from>2020</from>
      <owner>
        <organization>
          <name>International Organization for Standardization</name>
          <abbreviation>JCMG</abbreviation>
        </organization>
      </owner>
    </copyright>
  </bibdata></address>
  ```


cc: @ronaldtse

**Comment by opoudjis** [comment]
So `.adapter_node` is the workaround you had mentioned to Mapping Hash, that was preserving XML?

Ok, but why node.node.adapter_node? We will need documentation of the attributes of node in custom methods, so we know what to do with them.

The output you are generating looks plausible now, and I will update metanorma and test it.

**Comment by opoudjis** [comment]
... No: config.bibdata now processes correctly with that fix, but config.manifest also contains a bibdata attribute, and when that attribute is fetched, using the same custom method, config.manifest turns into a MappingHash instead of an object. That suggests that the old issue of failing to track recursion of model in custom calls is still there.

To replicate: 

PR fix/lutaml-model on https://github.com/metanorma/metanorma

The lutaml model code is:

lib/metanorma/collection/config/ : bibdata.rb config.rb converters.rb manifest.rb

You can replicate the issue by running  rspec spec/collection_spec.rb . I have a debug statement when a config XML is processed, containing both config.bibdata and config.manifest.bibdata

````
      def parse(file)
        # need @dirname initialised before collection object initialisation
        @dirname = File.expand_path(File.dirname(file))
        config = case file
                 when /\.xml$/
                   ::Metanorma::Collection::Config::Config.from_xml(File.read(file))
                 when /.ya?ml$/
                   y = YAML.safe_load(File.read(file))
                   pre_parse_model(y)
                   ::Metanorma::Collection::Config::Config.from_yaml(y.to_yaml)
                 end
        require 'debug'; binding.b
        new(file: file, config: config)
      end
````

`file` here is spec/fixtures/collection/collection1.xml : 

````
<metanorma-collection>
  <bibdata type="collection">
    <title type="title-main" format="text/plain" language="en">ISO Collection 1</title>
 ...
  </bibdata>
...
  <entry index="true">
    <identifier>_</identifier>
    <type>collection</type>
    <title>ISO Collection</title>
    <entry index="true">
      <identifier>_</identifier>
      <type>subcollection</type>
      <title>Standards</title>
      <entry index="true" fileref="rice-en.final.xml">
        <identifier>ISO 17301-1:2016</identifier>
        <bibdata type="standard">
          <title type="main" format="text/plain" language="en">Cereals and pulses — Specifications and test methods — Rice (Final)</title>
...
````

(`entry` is an alias of `manifest`)

I expect the retrieved config object to contain config.bibdata, config.manifest, and when I recursively travel down the tree of config.manifest entries, config.manifest....manifest.bibdata. But I am getting:

````
(rdbg) p config    # command
=> #<Metanorma::Collection::Config::Config:0x000000013b79ff90 

@bibdata=#<RelatonIsoBib::IsoBibliographicItem:0x000000013d816698 @abstract=[], @accesslocation=[], @biblionote=#<RelatonBib::BiblioNoteCollection:0x000000013d9dcfe0 @array=[]>, @classification=[], @contributor=[], @copyright=[#<RelatonBib::CopyrightAssociation:0x000000013a51e790 @from=#<Date: 2020-01-01 ((2458850j,0s,0n),+0s,2299161j)>, @owner=[#<RelatonBib::ContributionInfo:0x000000013d9d9ed0 @entity=#<RelatonBib::Organization:0x000000013a51f050 @abbreviation=#<RelatonBib::LocalizedString:0x000000013d9da1c8 @content="ISO", @language=nil, @script=nil>, @contact=[], @identifier=[], @logo=nil, @name=[#<RelatonBib::LocalizedString:0x000000013d9da268 @content="International Organization for Standardization", @language=nil, @script=nil>], @subdivision=[]>, @role=[#<RelatonBib::ContributorRole:0x000000013d9d9db8 @description=[], @type="publisher">]>], @scope=nil>], @date=[#<RelatonBib::BibliographicDate:0x000000013a591650 @from=nil, @on="2020-01-01", @to=nil, @type="created">, #<RelatonBib::BibliographicDate:0x000000013a5905c0 @from=nil, @on="2020-01-01", @to=nil, @type="issued">], @docidentifier=[#<RelatonBib::DocumentIdentifier:0x000000013a592d70 @id="ISO 12345", @language=nil, @primary=nil, @scope=nil, @script=nil, @type="iso">], @docnumber=nil, @doctype=nil, @edition=#<RelatonBib::Edition:0x000000013d9dd530 @content="1", @number=nil>, @editorialgroup=nil, @extent=[], @fast_track=nil, @fetched=nil, @horizontal=nil, @ics=[], @id="ISO12345", @id_attribute=true, @keyword=[], @language=[], @license=[], @link=[], @medium=nil, @place=[], @relation=#<RelatonBib::DocRelationCollection:0x000000013d9d56a0 @array=[]>, @script=[], @series=[], @size=nil, @stagename=nil, @status=nil, @structuredidentifier=nil, @subdoctype=nil, @title=#<RelatonBib::TypedTitleStringCollection:0x000000013d9b1070 @array=[#<RelatonBib::TypedTitleString:0x000000013d9b1368 @title=#<RelatonBib::FormattedString:0x000000013a5932c0 @content="ISO Collection 1", @format="text/plain", @language=["en"], @script=nil>, @type="title-main">]>, @type="collection", @validity=nil, @version=[]>, 

@compile=nil, @coverpage="cover.html", @directive=[#<Metanorma::Collection::Config::Directive:0x000000013d9d5100 @element_order=["text", "key", "text"], @key="documents-external", @mixed=nil, @ordered=nil, @using_default={:key=>false, :value=>true}, @validate_on_set=false, @value=nil>, #<Metanorma::Collection::Config::Directive:0x000000013a51cad0 @element_order=["text", "key", "text", "value", "text"], @key="coverpage", @mixed=nil, @ordered=nil, @using_default={:key=>false, :value=>false}, @validate_on_set=false, @value="spec/fixtures/collection/collection_cover.html">], @documents=[], @element_order=["text", "bibdata", "text", "directive", "text", "directive", "text", "entry", "text", "format", "text", "coverpage", "text", "prefatory-content", "text", "final-content", "text"], @final_content="\n    <clause id=\"_exordium\" inline-header=\"false\" obligation=\"normative\">\n      <title>Exordium</title>\n      <p id=\"\">Hic explicit</p>\n    </clause>\n  ", @format=["html"], 

@manifest={"text"=>["\n    ", "\n    ", "\n    ", "\n    ", "\n    ", "\n    ", "\n  "], "identifier"=>{"text"=>"_"}, "type"=>{"text"=>"collection"}, "title"=>{"text"=>"ISO Collection"}, "entry"=>[{"text"=>["\n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n      ", "\n    "], "identifier"=>{"text"=>"_"}, "type"=>{"text"=>"subcollection"}, "title"=>{"text"=>"Standards"}, "entry"=>[{"text"=>["\n        ", "\n        ", "\n      "], "identifier"=>{"text"=>"ISO 17301-1:2016"}, "bibdata"=>{"text"=>["\n          ", "\n          ", "\n          ", "\n          ", "\n          ", "\n          ", "\n          ", "\n          "
....
````

config.bibdata is an object, it parses fine. config.manifest is blowing up, it's a MappingHash instead of the expected Metanorma::Collection::Config::Manifest object.

**Comment by HassanAkbar** [comment]
@opoudjis the issue here is that in `collection/config/config.rb` we are using custom methods to generate the manifest and in that method, we are simply assigning the `mapping_hash` to the `model.manifest`. That is why it is not being converted into ruby objects. 

We can make it work by properly parsing the hash by changing it from

```ruby
def manifest_from_xml(model, node)
  model.manifest = node
end
```

to 

```ruby
def manifest_from_xml(model, node)
  model.manifest = Manifest.from_xml(node.node.to_xml)
end
```

but if we do it like this we can skip the custom methods here as this is the default behavior. Verified by using both approaches and collection test cases are passing both ways.

one more thing to change is to add a check for node presence in `bibdata_from_xml` like below

```ruby
def bibdata_from_xml(model, node)
  model.bibdata = Relaton::Cli.parse_xml(node.node.adapter_node) if node
end
```

**Comment by opoudjis** [comment]
I know this is deep magic, but we need documentation to explain this. This is like the delegate case (which I have had lots of difficulty understanding), but... well, I don't understand how it is different. OK.

**Comment by HassanAkbar** [comment]
@opoudjis I will add documentation for `mapping_hash.node` in this ticket -> https://github.com/lutaml/lutaml-model/issues/141

**Comment by ronaldtse** [comment]
This is done.
