### ISSUE TITLE
URGENT crash when require

### ISSUE THREAD

**Issue by andrew2net** [lutaml/lutaml-model#20]
This gem crashes when it's required because of missed dependency. The missed dependency is in the Gemfile. All the dependencies in the Gemfile are only available in testing mode. In runtime mode only dependencies in gemspec are available.
```
> require 'lutaml/model'
<internal:/Users/andrej/.rvm/rubies/ruby-3.3.3/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require': cannot load such file -- toml-rb (LoadError)
        from <internal:/Users/andrej/.rvm/rubies/ruby-3.3.3/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
        from /Users/andrej/.rvm/gems/ruby-3.3.3/gems/lutaml-model-0.2.1/lib/lutaml/model/toml_adapter/toml_rb_adapter.rb:2:in `<top (required)>'
        from /Users/andrej/.rvm/gems/ruby-3.3.3/gems/lutaml-model-0.2.1/lib/lutaml/model/serialize.rb:6:in `require_relative'
        from /Users/andrej/.rvm/gems/ruby-3.3.3/gems/lutaml-model-0.2.1/lib/lutaml/model/serialize.rb:6:in `<top (required)>'
        from /Users/andrej/.rvm/gems/ruby-3.3.3/gems/lutaml-model-0.2.1/lib/lutaml/model/serializable.rb:2:in `require_relative'
        from /Users/andrej/.rvm/gems/ruby-3.3.3/gems/lutaml-model-0.2.1/lib/lutaml/model/serializable.rb:2:in `<top (required)>'
        from /Users/andrej/.rvm/gems/ruby-3.3.3/gems/lutaml-model-0.2.1/lib/lutaml/model.rb:10:in `require_relative'
        from /Users/andrej/.rvm/gems/ruby-3.3.3/gems/lutaml-model-0.2.1/lib/lutaml/model.rb:10:in `<top (required)>'
```

**Comment by ronaldtse** [comment]
The toml output is only optional, so it should only be “require”’d when the TOML adapter is loaded.

**Comment by andrew2net** [comment]
Thank you @HassanAkbar! When will it be released?

**Comment by HassanAkbar** [comment]
@andrew2net Version `0.3.0` has been released with this fixed.
