### ISSUE TITLE
Custom methods and separate model

### ISSUE THREAD

**Issue by andrew2net** [lutaml/lutaml-model#83]
With separate model custom methods are called on that model:
```ruby
class Item
  attr_accessor :id
end

class BibItem < Lutaml::Model::Serializable
  model Item
  attribute :id, :string

  xml do
    root 'bibitem'
    map_element "id", to: :id, with: { to: :id_to_xml }
  end

  def id_to_xml(model, doc)
    doc[:did] =  model.id
  end
end

> BibItem.to_xml item
=> lutaml-model-0.3.10/lib/lutaml/model/xml_adapter/xml_document.rb:123:in `add_to_xml': undefined method `id_to_xml' for an instance of Item (NoMethodError)
```
We shouldn't move serialization methods to separate models.

**Comment by ronaldtse** [comment]
Thanks @andrew2net for finding this. Indeed the current behavior is incorrect. 

@HassanAkbar can you please help? Thanks.

**Comment by HassanAkbar** [comment]
@ronaldtse Sure, I'm looking into this

**Comment by ronaldtse** [comment]
Is this now fixed with #86?

**Comment by HassanAkbar** [comment]
@ronaldtse Just found a minor issue will fix that with the specs in https://github.com/lutaml/lutaml-model/pull/85,

**Comment by HassanAkbar** [comment]
@ronaldtse I believe this is now fixed. can we close this now?

**Comment by andrew2net** [comment]
@HassanAkbar with GH version I get this error now:
```ruby
class Item
  attr_accessor :id
end

class BibItem < Lutaml::Model::Serializable
  model Item
  attribute :id, :string

  xml do
    root 'bibitem'
    map_element "id", to: :id, with: { to: :id_to_xml, from: :id_from_xml }
  end

  def id_to_xml(model, doc)
    doc[:did] =  model.id
  end

  def id_from_xml(model, value)
    model.id = value
  end
end

> item = Item.new
> item.id = '123'
> BibItem.to_xml item
(irb):16:in `id_to_xml': wrong number of arguments (given 3, expected 2) (ArgumentError)
        from /Users/andrej/.rvm/gems/ruby-3.3.3/gems/lutaml-model-0.3.10/lib/lutaml/model/xml_adapter/xml_document.rb:123:in `add_to_xml'

**Comment by ronaldtse** [comment]
Closing since done in #92.
